# Generated by Django 4.0.6 on 2022-07-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userlog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='userID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='userName',
            field=models.CharField(max_length=70),
        ),
    ]
