# Generated by Django 4.0.6 on 2022-07-18 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_userlog_action_alter_userlog_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
