# Generated by Django 4.0.6 on 2022-07-18 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userlog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 9, 54, 41, 151718, tzinfo=utc)),
        ),
    ]
